language: node_js

node_js:
  - "4.1"

services:
  - mongodb

sudo: false

env:
  global:
    - CXX=g++-4.8
    - TRAVIS=true
    - DISPLAY=:99.0
    - CONFIG_PREFIX=`npm config get prefix`

cache:
  directories:
    - ~/.meteor

before_install:
  - "mkdir -p node_modules &"

  # install starrynight, so we can launch nightwatch and selenium
  - "npm install -g starrynight"

  # fire up xvfb on port :99.0
  - "sh -e /etc/init.d/xvfb start"

  # set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

  # install meteor
  - "curl https://install.meteor.com | /bin/sh"

  # give meteor a few seconds after installing
  - "sleep 60"

 - "cd playerpiano"

script: "starrynight run-tests --framework gagarin --webdriver http://localhost:9515 ./packages/*/tests/gagarin/**/*.js"
